name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: |
        echo ${{ secrets.DOCKER_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        #docker pull ghcr.io/github/sreimers/archlinux-mingw:latest
        #docker build . -t archlinux-mingw --cache-from ghcr.io/github/sreimers/archlinux-mingw:latest
        docker build . -t archlinux-mingw
        docker tag archlinux-mingw ghcr.io/sreimers/archlinux-mingw:1.0
        docker push ghcr.io/sreimers/archlinux-mingw:1.0
